//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public int ID { get; set; }
        public string County { get; set; }
        public string Fin_action { get; set; }
        public string AccountNumber { get; set; }
        public string ParcelNumber { get; set; }
        public Nullable<double> Tax_yr { get; set; }
        public Nullable<double> certnum { get; set; }
        public Nullable<System.DateTime> Issued_Date { get; set; }
        public Nullable<double> Face_Amount { get; set; }
        public Nullable<double> Interest_Rate { get; set; }
        public string Cert_Buyer { get; set; }
        public string Account_Status { get; set; }
        public string Cert_Status { get; set; }
        public string Deed_Status { get; set; }
        public Nullable<System.DateTime> Date_Redeemed_Cert { get; set; }
        public string TDA { get; set; }
        public Nullable<double> TDA_TAX_YR { get; set; }
        public Nullable<System.DateTime> Application_Date { get; set; }
        public Nullable<double> Applicating_Cert { get; set; }
        public Nullable<double> DeedAppNumber { get; set; }
        public string TDA_Deed_Status { get; set; }
        public string Applicant { get; set; }
        public string Deed_Sale_Date { get; set; }
        public string Sold_To_Applicant { get; set; }
        public Nullable<System.DateTime> TDA_Date_Redeemed { get; set; }
        public Nullable<double> Roll_Yr { get; set; }
        public Nullable<double> RedeemCount { get; set; }
        public Nullable<double> UnredeemCount { get; set; }
        public Nullable<double> MarketVal { get; set; }
        public Nullable<double> HomesteadType { get; set; }
        public string ExclusionCode { get; set; }
        public string PricingGroup { get; set; }
        public string luTitle { get; set; }
        public string age { get; set; }
        public string orig_action { get; set; }
    }
}
