//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int CNTYID { get; set; }
        public int CID { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string faxnumber { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public string notes { get; set; }
        public string cellphone { get; set; }
        public string ext { get; set; }
    }
}
