//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DORData
    {
        public int ID { get; set; }
        public string County { get; set; }
        public string ParcelNumber { get; set; }
        public Nullable<double> ASMNT_YR { get; set; }
        public string DOR_UC { get; set; }
        public Nullable<double> JV { get; set; }
        public Nullable<double> JV_HMSTD { get; set; }
        public Nullable<double> LND_SQFOOT { get; set; }
        public Nullable<double> DT_LAST_IN { get; set; }
        public string IMP_QUAL { get; set; }
        public Nullable<double> EFF_YR_BLT { get; set; }
        public Nullable<double> TOT_LVG_AR { get; set; }
        public string MKT_AR { get; set; }
        public string NBRHD_CD { get; set; }
        public string TWN { get; set; }
        public string RNG { get; set; }
        public string SEC { get; set; }
        public string CENSUS_BK { get; set; }
        public string PHY_ADDR1 { get; set; }
        public Nullable<double> PHY_ZIPCD { get; set; }
        public string ALT_KEY { get; set; }
        public string JV_Range { get; set; }
        public string Homestead { get; set; }
        public string Year_Built { get; set; }
        public string Neighborhood_Census { get; set; }
        public string DOR_Desc { get; set; }
        public Nullable<int> JV_Order { get; set; }
    }
}
