//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NJSub
    {
        public int ID { get; set; }
        public string APN { get; set; }
        public string Township { get; set; }
        public string Certnum { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public Nullable<double> Subsequent { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
