//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class percentCalc
    {
        public int ID { get; set; }
        public Nullable<int> morder { get; set; }
        public string action { get; set; }
        public string pchoice { get; set; }
        public string pchoice2 { get; set; }
        public string PricingGroup { get; set; }
        public Nullable<double> Face_Value { get; set; }
        public Nullable<double> Month_6 { get; set; }
        public Nullable<double> Month_12 { get; set; }
        public Nullable<double> Month_23 { get; set; }
        public Nullable<double> Month_30 { get; set; }
        public Nullable<double> Month_36 { get; set; }
        public Nullable<double> Today { get; set; }
        public string county { get; set; }
        public string nuser { get; set; }
    }
}
