//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportParam
    {
        public int ID { get; set; }
        public string County { get; set; }
        public string Fin_action { get; set; }
        public string Issued_Date { get; set; }
        public string gparam1 { get; set; }
        public string gparam2 { get; set; }
        public string qwparam1 { get; set; }
        public string qwparam2 { get; set; }
        public string JV_Range { get; set; }
        public string gddparam1 { get; set; }
        public string gddparam2 { get; set; }
        public string nuser { get; set; }
    }
}
