//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TowerEntities : DbContext
    {
        public TowerEntities()
            : base("name=TowerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<datatemplate> datatemplates { get; set; }
        public virtual DbSet<percentCalc> percentCalcs { get; set; }
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<DORData> DORDatas { get; set; }
        public virtual DbSet<ColName> ColNames { get; set; }
        public virtual DbSet<ReportParam> ReportParams { get; set; }
        public virtual DbSet<certData> certDatas { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<JerseyData> JerseyDatas { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<NJSub> NJSubs { get; set; }
    
        public virtual int spdataDownLoad(string sstring)
        {
            var sstringParameter = sstring != null ?
                new ObjectParameter("sstring", sstring) :
                new ObjectParameter("sstring", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spdataDownLoad", sstringParameter);
        }
    
        public virtual int spCounty(string pgroup, string pwhere, Nullable<int> pswitch, string puser, string pselect, string pselect2)
        {
            var pgroupParameter = pgroup != null ?
                new ObjectParameter("pgroup", pgroup) :
                new ObjectParameter("pgroup", typeof(string));
    
            var pwhereParameter = pwhere != null ?
                new ObjectParameter("pwhere", pwhere) :
                new ObjectParameter("pwhere", typeof(string));
    
            var pswitchParameter = pswitch.HasValue ?
                new ObjectParameter("pswitch", pswitch) :
                new ObjectParameter("pswitch", typeof(int));
    
            var puserParameter = puser != null ?
                new ObjectParameter("puser", puser) :
                new ObjectParameter("puser", typeof(string));
    
            var pselectParameter = pselect != null ?
                new ObjectParameter("pselect", pselect) :
                new ObjectParameter("pselect", typeof(string));
    
            var pselect2Parameter = pselect2 != null ?
                new ObjectParameter("pselect2", pselect2) :
                new ObjectParameter("pselect2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCounty", pgroupParameter, pwhereParameter, pswitchParameter, puserParameter, pselectParameter, pselect2Parameter);
        }
    
        public virtual int spMktVal(string pwhere, string puser)
        {
            var pwhereParameter = pwhere != null ?
                new ObjectParameter("pwhere", pwhere) :
                new ObjectParameter("pwhere", typeof(string));
    
            var puserParameter = puser != null ?
                new ObjectParameter("puser", puser) :
                new ObjectParameter("puser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spMktVal", pwhereParameter, puserParameter);
        }
    
        public virtual int spDrillDown(string countyname, string buy, string pVRange, string p1group, string p2group, string p1where, string p2where, string p3group, string p4group, string pissdt, string puser)
        {
            var countynameParameter = countyname != null ?
                new ObjectParameter("countyname", countyname) :
                new ObjectParameter("countyname", typeof(string));
    
            var buyParameter = buy != null ?
                new ObjectParameter("buy", buy) :
                new ObjectParameter("buy", typeof(string));
    
            var pVRangeParameter = pVRange != null ?
                new ObjectParameter("PVRange", pVRange) :
                new ObjectParameter("PVRange", typeof(string));
    
            var p1groupParameter = p1group != null ?
                new ObjectParameter("p1group", p1group) :
                new ObjectParameter("p1group", typeof(string));
    
            var p2groupParameter = p2group != null ?
                new ObjectParameter("p2group", p2group) :
                new ObjectParameter("p2group", typeof(string));
    
            var p1whereParameter = p1where != null ?
                new ObjectParameter("p1where", p1where) :
                new ObjectParameter("p1where", typeof(string));
    
            var p2whereParameter = p2where != null ?
                new ObjectParameter("p2where", p2where) :
                new ObjectParameter("p2where", typeof(string));
    
            var p3groupParameter = p3group != null ?
                new ObjectParameter("p3group", p3group) :
                new ObjectParameter("p3group", typeof(string));
    
            var p4groupParameter = p4group != null ?
                new ObjectParameter("p4group", p4group) :
                new ObjectParameter("p4group", typeof(string));
    
            var pissdtParameter = pissdt != null ?
                new ObjectParameter("pissdt", pissdt) :
                new ObjectParameter("pissdt", typeof(string));
    
            var puserParameter = puser != null ?
                new ObjectParameter("puser", puser) :
                new ObjectParameter("puser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDrillDown", countynameParameter, buyParameter, pVRangeParameter, p1groupParameter, p2groupParameter, p1whereParameter, p2whereParameter, p3groupParameter, p4groupParameter, pissdtParameter, puserParameter);
        }
    
        public virtual int spSubsequentUpdate(string puser)
        {
            var puserParameter = puser != null ?
                new ObjectParameter("puser", puser) :
                new ObjectParameter("puser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSubsequentUpdate", puserParameter);
        }
    }
}
